import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GradientText } from "./GradientText";
import { TextInput } from "../pages/TextInput";
import Examples from "../Components/application-ui/forms/select-menus/simple_custom";
import { RadioButton } from "./RadioButton";
import { CheckBox } from "./CheckBox";
import { SearchField } from "./SearchField";
import { SearchIcon } from "@heroicons/react/solid";
import { DropDownList } from "./DropDownList";
import { ListBox } from "./ListBox";

const arrayOfObjects = [
  {
    checkBoxLable: "aaaa",
    id: 1,
    checkBoxId: "xxx1",
    checkBoxValue: "bbb1",
    checkBoxName: "cccc1",
  },
  {
    checkBoxLable: "aaaa2",
    id: 2,
    checkBoxId: "xxx2",
    checkBoxValue: "bbb2",
    checkBoxName: "cccc2",
  },
  {
    checkBoxLable: "aaaa3",
    id: 3,
    checkBoxId: "xxx3",
    checkBoxValue: "bbb3",
    checkBoxName: "cccc3",
  },
];

const items = [
  { id: 1, name: "Wade Cooper" },
  { id: 2, name: "Arlene Mccoy" },
  { id: 3, name: "Devon Webb" },
  { id: 4, name: "Tom Cook" },
  { id: 5, name: "Tanya Fox" },
  { id: 6, name: "Hellen Schmidt" },
  { id: 7, name: "Caroline Schultz" },
  { id: 8, name: "Mason Heaney" },
  { id: 9, name: "Claudie Smitham" },
  { id: 10, name: "Emil Schaefer" },
];

const ListBoxitems = [
  { id: 1, name: "Wade Cooper" },
  { id: 2, name: "Arlene Mccoy" },
  { id: 3, name: "Devon Webb" },
  { id: 4, name: "Tom Cook" },
  { id: 5, name: "Tanya Fox" },
  { id: 6, name: "Hellen Schmidt" },
  { id: 7, name: "Caroline Schultz" },
  { id: 8, name: "Mason Heaney" },
  { id: 9, name: "Claudie Smitham" },
  { id: 10, name: "Emil Schaefer" },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-3 ">
        {/* <GradientText
          text="Yukthi Isuranga"
          h1Style=" col-span-3	"
          textStyle="italic text-9xl	"
        /> */}

        {/* <textField name="name" placeholder="yukthi isuranga" inputStyle="" /> */}
        <TextInput
          type="text"
          lable="Full Name"
          placeholder="yukthi isuranga"
          lableStyle="block text-sm font-medium text-gray-700 	"
          inputStyle="text-xl	"
          id="fname"
        />
        <TextInput
          type="number"
          lable="Phone Number"
          placeholder="12346789"
          lableStyle="block text-sm font-medium text-gray-700 	"
          inputStyle="text-xl	"
          id="phone"
        />
        <TextInput
          type="email"
          lable="Email"
          placeholder="admin@gmail.com"
          lableStyle="block text-sm font-medium text-gray-700 	"
          inputStyle="text-xl	"
          id="email"
        />
        <TextInput
          type="number"
          lable="Phone Number"
          placeholder="12346789"
          lableStyle="block text-sm font-medium text-gray-700 	"
          inputStyle="text-xl	"
          id="fname"
        />

        <RadioButton
          id="gender"
          items={["AAA", "BBB", "CCC", "DDD", "EEE"]}
          lable="Gender"
          lableStyle="block text-sm font-medium text-gray-700 "
        />

        <CheckBox
          items={arrayOfObjects}
          id="Name"
          lable="CheckBox"
          lableStyle="block text-sm font-medium text-gray-700"
        />

        <SearchField
          lable="Search fields"
          icon={
            <SearchIcon className="h-5 w-5 text-gray-400" aria-hidden="true" />
          }
          inputId="id"
          inputPlaceholder="Yukthi Isuranga"
        />

        <DropDownList items={items} label="DropDown List" />

        <ListBox lable="List Box" items={ListBoxitems} />
      </div>

      {/* <Examples/> */}

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
